<template>
	<div>
		<h2>Design-oriented, team-focued Front End Developer</h2>
		<h3>A Helluva non-Engineer</h3>
		<p>Growing up, I was always very math and science focused in school, but extra-curricularly interested in music and art. So, going to Georgia Tech seemed the obvious choice for an in-state math nerd, but I knew that I did not want to major in any form of traditional engineering. After first-year core classes and some soul searching, I landed on a major in Industrial Design. It seemed the perfect choice&mdash;a degree in product design that would require pragmatism and problem solving as well as a bucket of Prismacolor markers and archival pens. I spent countless hours in design studio, learning the ins and outs of freehand sketching, line art, graphic design and the Adobe Suite, 3D computer modeling, and iterative physical modeling. Meanwhile, I was taking classes about manufacturing, contracts, and sustainable design. All the while, I get a kick out of telling people that I go to Georgia Tech, but I'm not an engineer&mdash;not realizing that <em>I'm much more of an engineer than I think.</em></p>
		<p>Outside of the classroom, I worked as a Resident Advisor in freshman housing and was involved in the freshman orientation program, both of which allowed me to gain experience in building up leaders based on their own interests.</p>
		<img src="https://picsum.photos/720/480?image=1044">
		<!-- <ul>
			<li><strong>Throw in some portfolio shots</strong></li>
		</ul> -->

		<h3>Chile ......</h3>
		<p>The same passion for working with younger college students transitioned me to working on a team of like-minded recent grads all interested in college ministry. We worked for a year fund raising, then arrived in Santiago, Chile to fill in for the current team that was transitioning off the field. Not surprisingly, though, I couldn't leave my design roots. In an effort to better communicate to increasingly digitally-minded students, I was tasked with a full reboot of the ministry's brand and marketing materials.</p>
		<img src="https://picsum.photos/720/480?image=1044">
		<!-- <ul>
			<li><strong>EO brand pieces</strong></li>
		</ul> -->
		<p>My strength as a designer, minister, and friend flowed from my team&mdash;we were a very united and clearly focused team that enjoyed working together almost as much as we enjoyed being together outside of work. Our brainstorming sessions were productive, we learned how to maximize our meeting times (which decreased meeting frequency), and each member really pulled their weight. And yes, there was conflict, but we tried to head that off as often as possible through open and honest communication and bi-monthly "knees-to-knees" sessions designed to allow time to be open about interpersonal encouragement or struggle.</p>
		<p>My primary focus with students was building and developing leadership groups. Leaders were selected from students that showed interest and initiative beyond the normal commitment&dash;basically anyone that wanted to give back rather than simply receive. I built on my experiences from Georgia Tech freshman leadership building and really saw these groups explode. The model in prior years was to have the main ministry team decide on goals and service projects. I reshaped it to come from within the student leaders, which resulted in a much greater buy-in and participation, as well as just flat-out better ideas. This was a huge learning point for me in team building and motivation.</p>

		<h3>Graphic Design to Web Design to Web Developer</h3>
		<p>After three years in ministry, the next step of going to seminary seemed obvious. Due to my design background, I was able to get a GA position in the Dean's Office "redesigning" the web site. This, of course, meant more like a full site and content audit and a rework of the entire information architecture. Although, at the time this was my first foray into anything web-related, so I would not have used that language. But the needs were obvious enough. So, after putting in the work interviewing stakeholders and getting sign offs on the general flow of information, I got to work on the design. Not to mention, I began work on a rebrand of marketing materials and even the logo. Once design was approved and ready to code, I was asked if I could code it as well (because the student worker that would have done that was suddenly unable to). I have never been one to back down from an intellectual challenge, so though I had absolutely zero knowledge of web development, I said that I would give it a go. Given that there was a database and back end developer, I knew that I would mostly be working on reproducing the design. So, I started out by using <a href="//en.wikipedia.org/wiki/Microsoft_Expression_Web">Microsoft Essentials</a>, which tried to render HTML and CSS based off of .ai and .psd files. With that tool plus a lot of googling, I was able to officially launch my very first website! And although the code spit out by Expression Web was awful, I was able to see the patterns of what CSS was capable of...and I was hooked. I loved that I was able to turn my creations from a static Illustrator file into something that anyone in the world could interact with. And I loved that I could create a design system inside a CSS file (at this point, I'm nowhere near Atomic Design or Pattern Libraries&mdash;just like finding the least common denominators and creating classes for them). I also began to learn what could be translated well from a design comp to HTML/CSS and what could not.</p>
		<p>So now that I was hooked, I worked with my back end developer turned partner in crime to overhaul the school's entire web presence. We designed and built a recruiting and admissions site, an on-campus housing site, an online application for admission, and a portal for all students, faculty, and staff. With each new site, I learned more about what was good and helpful for my code base and the desire grew to do even better on the next site.</p>
		<p>Oh, and did I mention I was in school for a 60-hour Master's degree? Well, I was, and a few months before graduation, I had begun to apply for jobs when a front end position came open in a local digital agency. My trusty back end developer had actually left five months prior and was working at this agency, so when they needed a front end developer, he asked if I was interested.</p>

		<h3>Ntara</h3>
		<p>A lot changed when I moved to Ntara&mdash;for me and for Ntara. For Ntara, I was their first full-time front end developer. Up to then, they were able to contract out site builds and maintain the code base in-house. However, they had begun a responsive redesign for a regional ecommerce brand, so the stakes were much higher. For me, I never had any exposure to building responsive sites or even maintaining someone else's code. Though it was daunting, I was up for the challenge and dove in head-first.</p>
		<p>Through that first responsive site build, I learned the pros and cons of responsive frameworks (I used Foundation v.3), what works and what doesn't for CSS organization, and how to preempt errors in CMS content entry. I even got my first doses of version control, automated builds, and multiple environments. My biggest takeway, though, was that no matter the size of the hurdle, I could clear it.</p>
		<p>As our site portfolio grew, our designers started to really push the envelope. They abandoned the 960 grid and column&plus;gutter schema, which, coupled with the large amount of bloat present in responsive frameworks at the time, made me rethink using frameworks at all. It was clear that if I was going to keep up with the custom designs, I'd have to build my own "framework," so to speak. I took our most repeated and non-traditional design patterns and developed CSS and HTML snippets that would produce the desired effect and work well enough in older browsers. This was when I really started to love front end development because I could really exercise the math and systematic thought side of my brain.</p><!-- <span>Turned into a flex framework w/ IE9/10 fallbacks (before wider browser support and old browser deprecation)</span> -->
		<p>Soon after I had a stable version of my framework, which had featured on a few production sites, another front end developer joined the team. This was, of course, great. However, with regards to sharing code bases and explaining the framework, it was clear that we would learn a lot together. Over the following year, we added a lot of utility classes, trimmed some unnecessary code, and integrated bug fixes. We added support for older browsers and for accessibility. And finally, we began to <a href="//dimweightsolutions.com/docs">document and publish examples</a>. This&mdash;along with documentation of our internal front end processes&mdash;made the task of onboarding of new developers (front and back end) much simpler.</p>
		<h4>Small agency, less resoures</h4>
		<p>One unique challenge of working at a small agency was that my coworkers were often stretched pretty thin. So, with only a two-person design team, we often found ourselves with one or two mobile comps at best, which meant that we were tasked with filling in the gaps by designing in the browser. Luckily, my background in design allowed me to make informed decisions about how to scale and maintain integrity of the design.</p>
		<h4>Pattern Libraries</h4>
		<p>As our sites grew in size and complexity, I began to integrate <a href="//styleguides.io/">pattern libraries</a> into our workflow. I based much of my initial implementations on the thoughts of Brad Frost's (et al.) <a href="//patternlab.io/">Pattern Lab</a>, which was very formative for producing modular, scalable code. That paradigm also quickly became something that I taught to both design and back end. They saw the wisdom in the approach and we all worked together to streamline the design to development based around those ideas. Being able to interpret design cues and anticipate the HTML needs of back end was key to making this work.</p>
		<h4>Leadership of mini-department</h4>
		<p>As we continued to grow, I began to realize that as a small group of developers, we front end developers needed someone to advocate for our needs. Our director was in charge of evenyone in production, so we didn't have someone that understood our concerns and needs. So, I developed a plan to grow the team through mentorships, professional development plans, code reviews, and staying on top of current trends. <a href="//www.ntara.com/Blog/September-2016/How-to-Build-a-Front-End-Team" target="_blank">I even wrote about it</a>.</p>
		<h3>The next great thing</h3>
		<p>So that's it. That's the &ldquo;quick&rdquo; version of the story about how a seminary-trained missionary found himself hooked on web development. Bullet points are nice and succinct, but you'd be forgiven for being confused by their trajectory.</p>
	</div>
</template>

<script>
</script>

<style scoped lang="scss">

</style>